Feature: added Result.run_id
synthesized-io/insight pull request #141
Opened 2023-09-14 12:13 UTC by marqueewinq

Currently the insight package populates the Results without any grouping except created_at date. I'm adding `Result.run_id` to fix that.

2023-09-14 12:38 UTC, marqueewinq commented
> [![28.6%](https://camo.githubusercontent.com/8f6686cb3d0947decfd92115e15fd4cd1d205e261a5e90a28f193db2a2ad4719/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f32352d313670782e706e67)](https://sonarcloud.io/component_measures?id=synthesized-io_synthesized-insight&pullRequest=141&metric=new_coverage&view=list) [28.6% Coverage](https://sonarcloud.io/component_measures?id=synthesized-io_synthesized-insight&pullRequest=141&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=synthesized-io_synthesized-insight&pullRequest=141&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=synthesized-io_synthesized-insight&pullRequest=141&metric=new_duplicated_lines_density&view=list)
> 

Perhaps we need to disable coverage for migrations

2023-09-15 08:46 UTC, simonhkswan requested changes
I've left one question about the _add_to_database function. But the rest all looks great! Once we've addressed that one Q we can definitely merge.

2023-09-15 08:46 UTC, simonhkswan commented on README.md
> +
👍🏼

2023-09-15 08:46 UTC, simonhkswan commented on src/insight/alembic/main.py
> +] + args
Ah, nice way to update this.

2023-09-15 08:46 UTC, simonhkswan commented on src/insight/metrics/base.py
> +                         run_id: str = None):
Given that `version` is obtained from the an envrionment variable, does it make sense for run_id to also be obtained in the same way? (See lines 83:84 of this file).

Also I've just noticed that line 81: should probably be removed and replaced with run_id if we leave `run_id` as an argument.

2023-09-15 14:02 UTC, simonhkswan approved these changes
Nice work! Thanks for making that change.

2023-09-15 14:13 UTC, merged